### ISSUE TITLE
New URL formats have broken embedding

### ISSUE THREAD

**Issue by LauraMakesArt** [sketchfab/vanilla-plugin#6]
Our client using sketchfab extensively reports that the plugin has stopped functioning since the URLs changed format, they provided these examples below: 

Pasting a current url in the embedder prevents the "Continue" button from functioning:
https://sketchfab.com/3d-models/not-scared-3dbustchallenge-b7e3047c3c6d4c419015cd98c58d4aba

Pasting an old url doesn't work either:
https://sketchfab.com/models/2f796cc40d3c4fe6af3c087d23f82124

**Comment by PadreZippo** [comment]
Thanks for the report. We'll get that fixed!

**Comment by PadreZippo** [comment]
Should be fixed by https://github.com/sketchfab/vanilla-plugin/pull/7

Could you let me know?

**Comment by LauraMakesArt** [comment]
Thanks @PadreZippo, we'll need to deploy on our end before we can test, I'll report back when we've confirmed!

**Comment by nervoustwit** [comment]
I have deployed this change and everything sketchfab URL I put in returns a 404. Is this a problem with the code, configuration? see https://polycount.com/discussion/121133/sketchfab-test#latest

**Comment by PadreZippo** [comment]
Hmm strange. It looks like it's turning

https://sketchfab.com/3d-models/cube-test-442c548d94744641ba279ae94b5f45ec

into

https://sketchfab.com/models/cube-test-442c548d94744641ba279ae94b5f45ec/embed?autostart=0

instead of

https://sketchfab.com/models/442c548d94744641ba279ae94b5f45ec/embed?autostart=0

I guess my fix for the regular expression was not enough, we also need to update where it fetched the Model ID, e.g.

https://github.com/sketchfab/vanilla-plugin/blob/27c8fd91000eec6da0b3093c715f2721f7e9db2c/js/sketchfab.js#L230

We're on it. Sorry about that!

**Comment by PadreZippo** [comment]
Looks like this is finally solved by #9
